### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hosseinyadollahi** [pumukit/PuMuKIT#326]
Hi 
I cant install on ubuntu 18
I installed it on ubuntu 20
when trying to run this command " php bin/console doctrine:mongodb:schema:create"

the result is this error :: "No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'db']"

please help me to solve this

**Comment by albacodina** [comment]
Hi,

Are you using Dockers? Because if not, the problem is that it cannot find the BD.

And another thing you should know, the latest stable version is 3.5.x.

I hope I have helped you in your query.

**Comment by hosseinyadollahi** [comment]
Hi
I used your Installation Manual
just Install on ubuntu 20 and phpfpm7.4 
and I don't what should I do now
Thanks for your reply

**Comment by albacodina** [comment]
Are you using the 3.5.x version? Or master?

**Comment by hosseinyadollahi** [comment]
master
How can I use 3.5 version
?
Thanks again for your fast reply

**Comment by albacodina** [comment]
When you clone the project, the branch is master. You need to change to 3.5.x version.

For this, you must run:

> git checkout 3.5.x

And then you can start the installation.

**Comment by hosseinyadollahi** [comment]
Thanks for your reply
I will try
Thanks
