### ISSUE TITLE
Docker Issue(s)

### ISSUE THREAD

**Issue by Open2Serve** [pumukit/PuMuKIT#343]
Hello, 
i'm trying to test your application through docker but, 
i'm facing of a lot off symphony error.

![image](https://user-images.githubusercontent.com/80029009/110126317-98781280-7dc4-11eb-8c48-2c48bb3c9a82.png)

Do you have an idea for me ? Or Could you please tell me what i've done wrong ? 

What i've done:

1. # comment all the line link to dev env in docker-compose.yml
2. type docker-compose up -d in the main folder 
(ps: i edit the port of the h2-proxy container because i've got a nginx proxy manager to manage all dns request on my docker little infra.

Kind Regards,

**Comment by insad** [comment]
Had exactly same problem outside docker because for not having my domain in TRUSTED_HOSTS in .env.local .... found it in the var/log/dev.log file.

**Comment by albacodina** [comment]
This problem has been solved.
