### ISSUE TITLE
Issue while deleting the MO which is under execution 

### ISSUE THREAD

**Issue by ukmothukuri** [pumukit/PuMuKIT#388]
And showing the status as executing for the past 3 days. If i try to delete the video, it is displaying the message as show below.
Bad Request, Cannot delete the multimedia object with id.., It has 1 job executing.

Please guide me to delete this video, as other queued videos are in waiting state for so long.

**Comment by Yurujai** [comment]
Hi @ukmothukuri,

To eliminate the job that is running we do not have a functionality that allows it easily (we hope to have it soon).

At the moment, the way to stop the job is to access the MongoDB and update the status of the job to ERROR.

To do this, connect to MongoDB, and update the Job with the following query ( you need replace the ObjectID on _id setting your Job ID )

`db.Job.update({'_id': ObjectId("612f4f968b1880017c4de2b7")}, {$set: {'status': -1}});`

You have more information about Job status on: https://github.com/pumukit/PuMuKIT/blob/3.7.x/src/Pumukit/EncoderBundle/Document/Job.php#L15-L19

You can find the ObjectID of your Job accessing to de "backoffice" and going to the "Encoder jobs" menu. Then you can show your job, and get more info ( id, status, mm...) about it on "i" icon.

Pd: Sorry for the delay.
