### ISSUE TITLE
Please update installation documentation

### ISSUE THREAD

**Issue by jplahti** [pumukit/PuMuKIT#522]
Installation documentation needs updating. Please document installation at least on Ubuntu 20.04 LTS and using latest MongoDB.

**Comment by j-lorenzo** [comment]
> Installation documentation needs updating. Please document installation at least on Ubuntu 20.04 LTS and using latest MongoDB.

I think it could be useful too add the docker installation steps, or maybe the docker compose in the documentation, meanwhile check this out https://github.com/pumukit/PuMuKIT/blob/master/docker-compose.yml

**Comment by Yurujai** [comment]
Yes, we are working to updated documentation with new installation methods. Thanks @j-lorenzo 

> > Installation documentation needs updating. Please document installation at least on Ubuntu 20.04 LTS and using latest MongoDB.
> 
> I think it could be useful too add the docker installation steps, or maybe the docker compose in the documentation, meanwhile check this out https://github.com/pumukit/PuMuKIT/blob/master/docker-compose.yml

Yes, we are working to update documentation adding new installation method with dockers.

**Comment by Yurujai** [comment]
Hi,

We have a new PR with new documentation usign dockers.


[1] https://github.com/pumukit/PuMuKIT-doc/pull/9
