### ISSUE TITLE
Backoffice: Backoffice: In series view the pagination of MO does not work correctly

### ISSUE THREAD

**Issue by silviabf** [pumukit/PuMuKIT#9]
Steps to reproduce:
- Go to backoffice
- Enter in any series
- Click on new to create a MO (if there is not any MO in the series you must create 2 MOs)

Branch: master

Desired result:
The MO are viewed in the same page of the backoffice (10 MO in every page by default)

Achieved result:
There is a page for any MO in the series and you can only navigate in the last page of the series (see attached picture) and work with the last MO that you created

![backoffice_error](https://user-images.githubusercontent.com/11191010/71244383-aaca7580-2312-11ea-8c26-abdadff68fb0.png)

**Comment by starzle** [comment]
Pagination problem also happens when the user is trying to view videos in a Series. Only one video will be displayed to the user.

**Comment by starzle** [comment]
After some research, I found that https://github.com/pumukit/PuMuKIT/commit/b07e4d55f1d1c15db852d68de420e44ad4250d24 is the culprit. Reverting the commit can fix the pagination issue (But it then causes another 500 error when I try to visit /admin/series/ page).

So I guess, this bug fix commit itself may have some bugs. @pepeportela please take a look at your commit and see if you can figure out why. Thank you very much.

**Comment by Yurujai** [comment]
Pull request created to fix pagination error. https://github.com/pumukit/PuMuKIT/pull/16

**Comment by Alfro** [comment]
QA.

**Comment by silviabf** [comment]
Fixed in master branch. Pagination is working correctly now. I close this issue.
